name: PyInstaller

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller transliterate
    - name: Build with pyinstaller
      run: |
        cmd /c 'python -c "import transliterate as t, os;t=t.__file__;os.system(''pyinstaller --onefile --add-data {};transliterate --add-data lang.json;. main.py''.format(t[:t.index(''\\'')]))"'
    - name: Upload compiled file
      uses: actions/upload-artifact@v3
      with:
        name: main.exe
        path: dist/main.exe
